spring.application.name=vtn

server.port=8080



#url=https://mm-controle.ceesp.ufsm.br/events
#username=ceesp
#password=micromobilidade

url=https://nhs-nupedee.ceesp.ufsm.br
username=ceesp
password=micr0mobilidad3



spring.datasource.url=jdbc:postgresql://localhost:5432/vtn_ufsm_e2g
spring.datasource.username=postgres
spring.datasource.password=2016010124


spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.datasource.driver-class-name=org.postgresql.Driver


logging.level.org.flywaydb=DEBUG